### ISSUE TITLE
QA_To understand the effect of chiral substances on plane polarized light as a function of wavelength_Introduction_video-needs-to-be-included

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/circular-dichronism-spectroscopy-iiith#42] opened 2017-05-29 05:40 UTC
Defect Description :
In the "Introduction" section of "To understand the effect of chiral substances on plane polarized light as a function of wavelength"experiment this lab, Video is not included while porting. Where as the video is given in the vlabs page.

Actual Result :
In the "Introduction" section of "To understand the effect of chiral substances on plane polarized light as a function of wavelength"experiment this lab, Video is not included while porting. Where as the video is given in the vlabs page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_cds_i07](https://cloud.githubusercontent.com/assets/13479177/26537745/755f18fe-445f-11e7-8d8b-fd28ea740aff.png)

**Comment by sravanthimodepu** [comment] 2017-07-04 09:23
This issue need to be fixed by system's team. Hence keeping the issue is on hold.

**Closed** 2018-10-12 09:48 UTC
Labels: Developed by: VLEAD, Open-Edx, Severity :S1, Status: Onhold, category : UI
